### ISSUE TITLE
/docs/pages/api-reference/next-config-js/assetPrefix.mdx 문서 번역

### ISSUE THREAD

**Issue by wlstmd** [luciancah/nextjs-ko#108]
`이슈를 작성하시기 전에 [기여 가이드[(https://nextjs-ko.org/contribution)을 먼저 확인해주세요.`

**기여 내용**

- [ ] 새로운 문서 번역
- [x] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
`e.g. /docs/pages/api-reference/next-config-js/assetPrefix.mdx`

**Comment by luciancah** [comment]
@wlstmd 안녕하세요. 이미 번역이 진행된 문서로 보이는데요, 어떤 이슈를 열어주신걸까요?

**Comment by wlstmd** [comment]
오잉 번역이 된거군요.. 
![스크린샷 2024-08-05 오후 8 11 44](https://github.com/user-attachments/assets/e69816a5-17ff-49d5-a310-65dd2c36de71)
보다가 Good to know 부분이 혼자 영어로 되있어서 불편해가지고.. 이부분을  commit 했었어요

**Comment by luciancah** [comment]
아하 새로운 문서 번역 태그가 달려있어서 제가 오해했습니다 ;)
수정해 주신다면 큰 도움이 될 것 같습니다

**Comment by wlstmd** [comment]
그 제가 포크해서 이슈랑 PR생성은 처음해서 그런데 어떤걸 수정해야하는건가요..?!

**Comment by luciancah** [comment]
말씀주신대로 아직 미 번역된 부분이나, [용어집](https://github.com/luciancah/nextjs-ko/issues/18) 에 맞지 않는 단어 사용, 어색한 문장 구조 등 번역 문서에 개선을 위한 방향이라면 가리지 않고 기여받고 있습니다.

**Comment by wlstmd** [comment]
아 넵! :)

**Comment by wlstmd** [comment]
docs/pages/api-reference/components/image-legacy.mdx파일 추가로 번역해도 될까요??
