### ISSUE TITLE
사전 지식 섹션 내용의 링크 버그 제보

### ISSUE THREAD

**Issue by IDKNWHORU** [luciancah/nextjs-ko#121]
`저는 기여 가이드를 충분히 읽어 봤습니다. 하지만 이 이슈는 어떻게 해결할지 대화 후 해결하는게 좋다고 생각해서 올립니다!`

## 기여 내용 

- [X] 버그 제보

## 문서 경로
`/docs/getting-started`

## 버그 내용

사전 지식 섹션에 있는 **React Foundations Course**, **대시보드 애플리케이션 구축** 링크를 클릭했을 때 404 NotFound 에러가 발생함.

![image](https://github.com/user-attachments/assets/e592c629-e7b5-4d04-aea4-0f488f03ab5a)

![image](https://github.com/user-attachments/assets/54db86e8-f854-42da-89d8-71c1223b93b7)

## 버그의 원인으로 생각되는 부분

https://github.com/luciancah/nextjs-ko/blob/main/pages/docs/index.mdx 파일을 참고할 것

사전 지식 섹션에 있는 링크의 폴더가 없음 (**/learn/react-foundations**, **/learn/dashboard-app**)

```mdx
## 사전 지식

우리의 문서는 초보자 친화적으로 설계되었지만, 문서가 Next.js 기능에 집중할 수 있도록 기본적인 지식을 확립할 필요가 있습니다. 새로운 개념을 도입할 때마다 관련 문서에 대한 링크를 제공하겠습니다.

문서를 최대한 활용하려면 HTML, CSS 및 React에 대한 기본적인 이해가 필요합니다. React 기술을 보충해야 하는 경우, [React Foundations Course](/learn/react-foundations)를 확인하여 기본을 익히세요. 그런 다음, [대시보드 애플리케이션 구축](/learn/dashboard-app)을 통해 Next.js에 대해 더 알아보세요.
```

### 대화 하고 싶은 부분
지금 이슈처럼 폴더의 경로에 문서가 없는 경우는 어떻게 해결해야 될까요?

**Comment by luciancah** [comment]
안녕하세요! 제보해주셔서 감사합니다.
사실 검색 인덱싱에서 내부 링크 404가 점점 증가해 SEO에 있어서도 악영향을 끼치는 부분이라 인지하고 있는 상황이긴 합니다.

현실적인 문제는 두 가지로 생각하고 있는데요,
1. vercel/nextjs 레포에서 https://github.com/vercel/next.js/blob/canary/learn/react-foundations 등 /learn 의 원본 문서를 제공하지 않고 있는 점
2. 우리 문서는 <Link /> 등 링크를 위한 외부 컴포넌트 사용 않고 md 문법의 link를 사용하고 있어 문서의 직접 수정이 필요하다는 점
입니다.

해결할 수 있는 방안은 해당 링크를 nextjs 영어 원본으로 보내는 편이 현실적일 것 같은데, mdx 상에서 할 수 있는 방법이 있는지 우선 리서치 해보겠습니다. 감사합니다.

**Comment by IDKNWHORU** [comment]
빠른 답변 감사합니다!

제 생각에는 /learn에 해당하는 문서도 공유하는게 좋겠다란 생각을 해봤었는데, 답변을 읽어보니 쉽게 생각해서 행동할만한게 아니네요..

열정에 감탄합니다! 건승하세요.

**Comment by IDKNWHORU** [comment]
일단 NextJS 질문 게시글에 learn 폴더에 해당하는 내용을 찾을 수 있는 방법에 대해 질문글을 생성해놨습니다. 변경사항이 있을 때 코멘트 남겨 놓겠습니다!

질문글 링크: https://github.com/vercel/next.js/discussions/68791

**Comment by IDKNWHORU** [comment]
learn에 대한 일부 레포를 찾았습니다. 이 내용으로 번역을 해 볼수도 있겠어요

https://github.com/vercel/next-learn

**Comment by IDKNWHORU** [comment]
질문글에 이런 답변이 달려서 공유합니다!

> I think some of the learn material is not yet open source, or might never be.
Here, https://github.com/vercel/next-learn you can find some of the code for the examples in the learning material. I think you can open an issue there, and ask more about how to be able to contribute with translations.

**Comment by luciancah** [comment]
안녕하세요! 시간과 애정 쏟아주셔서 항상 감사합니다. ;) 제가 월요일까지 휴가중이라서, 다녀와서 빠르게 팔로업 하겠습니다! 😊

**Comment by luciancah** [comment]
안녕하세요! 스레드에 달아두신 내용 확인 완료했습니다.

먼저 제 의견으로는 .. 지금과 같이 `/learn` 디렉토리의 원본 문서가 확인되지 않는 상황에서는, 번역 프로젝트를 모집 및 진행하기에는 현실적인 어려움이 조금 있을 것 같습니다.

반면에 `/learn` 과 동일한 이슈로, `/error` 디렉토리에 해당하는 문서 또한 아직 미번역 상태인데요, 이 부분은 nextjs 웹사이트에서도 네비게이션 없이 검색 쿼리로만 접근하는 것으로 인지하고 있습니다.

해당 문서에 대한 파일은 nextjs에서 제공하고 있어서, [next.js/errors](https://github.com/vercel/next.js/tree/canary/errors) 이쪽 문서는 새로 번역하고, `/learn` 경로에 해당하는 문서들은 (찾거나) 제공할 때 까지 외부 링크로 변환하는 것이 어떨까 의견 드립니다 !

항상 감사합니다 :)

**Comment by IDKNWHORU** [comment]
좋은 의견이라고 생각합니다!

저도 감사합니다ㅎㅎ

**Comment by IDKNWHORU** [comment]
이 이슈는 닫겠습니다

**Comment by luciancah** [comment]
네 감사합니다 :) 이후 로드맵에 우선적으로 포함시키도록 하겠습니다.
