### ISSUE TITLE
미번역 페이지 번역 요청

### ISSUE THREAD

**Issue by blueline1984** [luciancah/nextjs-ko#122]
https://nextjs-ko.org/docs/pages/api-reference/functions/use-amp
https://nextjs-ko.org/docs/pages/api-reference/components/head
https://nextjs-ko.org/docs/pages/building-your-application/Routing

해당 페이지 번역 진행되지 않았으면 번역 참여 가능할까요?

**Comment by luciancah** [comment]
@blueline1984 안녕하세요! 제가 확인을 놓친 페이지가 있었던 것 같네요. ㅠㅠ 기여는 항상 환영입니다 ;) [이쪽 이슈](https://github.com/luciancah/nextjs-ko/issues/6) 에서 기존에 작업하신 내역 확인해 보시면 빠르게 작업 시작하시는 데 도움 되실 것 같습니다. 감사합니다!

**Comment by luciancah** [comment]
새 이슈 생성하신 것 확인해서 이쪽은 닫겠습니다 :)
