### ISSUE TITLE
/docs/pages/api-reference/functions/use-amp

### ISSUE THREAD

**Issue by blueline1984** [luciancah/nextjs-ko#123]
**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
`/docs/pages/api-reference/functions/use-amp`

**Comment by blueline1984** [comment]
@luciancah 혹시 pr 제출은 main으로 하면 될까요?

**Comment by luciancah** [comment]
> @luciancah 혹시 pr 제출은 main으로 하면 될까요?

넵 메인으로 부탁드립니다. 제가 정기적으로 많은 PR 한번에 머지할때는 브랜치 새로 만들어서 스쿼시 하고 있습니다.

**Comment by blueline1984** [comment]
@luciancah 님 혹시~~ PR 후 추가적으로 해야할 사항이 있을까요? :)

**Comment by luciancah** [comment]
@blueline1984 안녕하세요~! 제가 다른 일로 PR 확인이 밀려 있었습니다 . ㅎㅎ 빠르게 리뷰 드리겠습니다 :)
