### ISSUE TITLE
/docs/pages/api-reference/components/head

### ISSUE THREAD

**Issue by blueline1984** [luciancah/nextjs-ko#124]
**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
`/docs/pages/api-reference/components/head`

**Comment by luciancah** [comment]
이슈 생성해주신 것 확인해 일단 어사인 드렸는데요, 혹시 use-amp 문서만 먼저 번역하시고, 다른 커뮤니티 분들에게 작업 양보하시고 싶으시다면 코멘트 주시면 다시 돌려두겠습니다 ! 감사합니다 :)

**Comment by HarrySeop** [comment]
괜찮다면 하나 할당 받고싶습니다! 블루라인님 코멘트 보고 이슈 생성하도록 하겠습니다!

**Comment by blueline1984** [comment]
@luciancah 넵! 답이 늦었네요! 해당 이슈 @HarrySeop 님에게 할당해주시면 될것같습니다 :)

**Comment by luciancah** [comment]
> @luciancah 넵! 답이 늦었네요! 해당 이슈 @HarrySeop 님에게 할당해주시면 될것같습니다 :)

감사합니다 😃 
@HarrySeop 어사인 드렸습니다! 잘 부탁드리겠습니다. :)

**Comment by HarrySeop** [comment]
넵 저도 잘 부탁드립니다! 이슈는 이대로 두고 진행하면 될까요 아니면 새로 만들고 문서 번역 이슈에 코멘트 남겨둘까요?? @luciancah

**Comment by luciancah** [comment]
> 넵 저도 잘 부탁드립니다! 이슈는 이대로 두고 진행하면 될까요 아니면 새로 만들고 문서 번역 이슈에 코멘트 남겨둘까요?? @luciancah 

할당 드렸으니 여기서 진행하셔도 될 것 같습니다.!
