### ISSUE TITLE
App route -> routing -> route handler -> cors 문서 형식 깨짐

### ISSUE THREAD

**Issue by KIMSEUNGGYU** [luciancah/nextjs-ko#126]
`이슈를 작성하시기 전에 [기여 가이드[(https://nextjs-ko.org/contribution)을 먼저 확인해주세요.`

**기여 내용**

- [ ] 새로운 문서 번역
- [x] 문서 내용 수정
- [x] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
- https://nextjs-ko.org/docs/app/building-your-application/routing/route-handlers#cors , 한글화 문제 부분

**문제**
>  문서의 형식이 깨져 있습니다. 

- 한글화 작업본 (이슈 부분)
<img width="900" alt="image" src="https://github.com/user-attachments/assets/eb3700e4-4bd7-4922-87e4-3e6b07d1ca46">

- NextJS 공식문서
<img width="683" alt="image" src="https://github.com/user-attachments/assets/c6258db8-9cc6-4884-9f8e-7d0742f24176">

**Comment by KIMSEUNGGYU** [comment]
> 문서의 형식이 깨져있어 수정하려고 하는데 Issue 등록하고 해야하는지 궁금합니다.

**Comment by luciancah** [comment]
안녕하세요! 간단한 수정이지만 프로젝트 메인테인의 용이성을 위해서 지금처럼 이슈 등록 부탁드리겠습니다. 찾아주셔서 감사합니다 :)
