### ISSUE TITLE
/docs/pages/building-your-application/configuring/amp.mdx 문서 번역

### ISSUE THREAD

**Issue by icefoxand** [luciancah/nextjs-ko#16]
`이슈를 작성하시기 전에 [기여 가이드[(https://nextjs-ko.org/contribution)을 먼저 확인해주세요.`

**기여 내용**

- [x] 새로운 문서 번역
- [ ] 문서 내용 수정
- [ ] 오타 수정
- [ ] 문서 웹페이지 기능 수정
- [ ] 기타 기능 개선 및 수정

**문서 경로**
'/docs/pages/building-your-application/configuring/amp.mdx'

해당 페이지 번역 진행하겠습니다.
기여 가이드 참고하여 일주일내로 PR 올리겠습니다!

**Comment by luciancah** [comment]
안녕하세요! 가이드 안내에 따라 원활한 프로젝트 진행을 위해 작업 할당 후 1주일 이내 작업 완료를 원칙으로 하고 있습니다. 8월 4일까지 작업 부탁드리겠습니다. :)
