### ISSUE TITLE
[감사합니다 🥰] Next.js v15.0.0-canary.82 문서 초안 번역

### ISSUE THREAD

**Issue by luciancah** [luciancah/nextjs-ko#6]
### 다음은 현재 번역되지 않은 문서의 목록입니다.
- 메인테이너가 주기적으로 확인 후 할당 된 문서에 체크하고 있습니다.
- 해당 문서 중 작업 하고 싶으신 사항을 `스레드에 댓글`로 남겨주신 후 `이슈를 생성`해주세요.
- 할당 후 1주일 내 작업이 완료되지 않는 경우 부득이하게 할당을 취소하겠습니다.

### 용어집 생성에도 도움이 필요합니다.
- 현재 routing / 경로 / 라우팅 등 빠르게 초안 번역을 진행하다 보니 용어 정리가 진행되지 않은 부분이 많습니다.
- 용어집 생성 및 추가나 용어집에 따른 전체적인 문서 수정에 도움 및 아이디어를 주실 분은 [이쪽 이슈](https://github.com/luciancah/nextjs-ko/issues/18)를 확인해주세요.

### 완료된 문서
- `/docs/pages/building-your-application/configuring/babel.mdx` @kmsu44 
- `/docs/pages/building-your-application/rendering/client-side-rendering.mdx` @4anghyeon 
- `/docs/pages/building-your-application/rendering/server-side-rendering.mdx` @hansololiviakim 
- `/docs/pages/building-your-application/data-fetching/get-static-paths.mdx` @gkfyr 
- `/docs/pages/building-your-application/configuring/debugging.mdx` @Hongheesun
- `/docs/pages/building-your-application/configuring/error-handling.mdx` @Hongheesun 
- `/docs/pages/building-your-application/deploying/ci-build-caching.mdx` @pySoo 
- `/docs/pages/building-your-application/upgrading/version-13.mdx` @hansololiviakim 
- `/docs/pages/building-your-application/routing/dynamic-routes.mdx` @aken-you 
- `/docs/pages/building-your-application/data-fetching/get-static-props.mdx` @f0rever0 
- `/docs/pages/building-your-application/routing/custom-error.mdx` @imdaxsz 
- `/docs/pages/building-your-application/data-fetching/get-server-side-props.mdx` @jiyeon2536 
- `/docs/pages/building-your-application/data-fetching/client-side.mdx` @daejlee 
- `/docs/pages/building-your-application/routing/custom-app.mdx` @gkfyr 
- `/docs/pages/building-your-application/configuring/custom-server.mdx` @dlsxjzld 
- `/docs/pages/building-your-application/rendering/static-site-generation.mdx` @gouz7514 
- `/docs/pages/api-reference/next-config-js/runtime-configuration.mdx` @therealjamesjung 
- `/docs/pages/building-your-application/data-fetching/forms-and-mutations.mdx` @ironAiken2 
- `/docs/pages/building-your-application/Rendering.mdx` @grapefruit13 
- `/docs/pages/building-your-application/routing/custom-document.mdx` @yoonncho 
- `/docs/pages/building-your-application/configuring/post-css.mdx` @SoJuSo 
- `/docs/pages/building-your-application/upgrading/version-12.mdx` @RedBe-an 
- `/docs/pages/building-your-application/configuring/preview-mode.mdx` @pySoo 
- `/docs/pages/building-your-application/upgrading/version-10.mdx` @miraexhoi 
- `/docs/pages/building-your-application/upgrading/version-11.mdx` @miraexhoi 
- `/docs/pages/api-reference/functions/get-server-side-props.mdx` @hansololiviakim 
- `/docs/pages/building-your-application/styling/css-modules.mdx` @Zero-1016 
- `/docs/pages/building-your-application/data-fetching/incremental-static-regeneration.mdx` @imdaxsz 
- `/docs/pages/building-your-application/routing/linking-and-navigating.mdx` @yoouyeon 
- `/docs/pages/building-your-application/rendering/automatic-static-optimization.mdx` @SoJuSo 
- `/docs/pages/api-reference/functions/get-static-props.mdx` @grapefruit13 
- `/docs/pages/building-your-application/routing/api-routes.mdx` @kor-bim 
- `/docs/pages/api-reference/functions/use-router.mdx` @WaterMinCho 
- `/docs/pages/building-your-application/routing/pages-and-layouts.mdx` @jinlee0310 
- `/docs/pages/api-reference/components/image-legacy.mdx` @wlstmd
- `/docs/pages/building-your-application/configuring/draft-mode.mdx` @pySoo 
- `/docs/pages/building-your-application/routing/internationalization.mdx` @davindev 
- `/docs/pages/api-reference/functions/get-initial-props.mdx` @hyunmyungJaneLee 
- `/docs/pages/building-your-application/upgrading/version-9.mdx` @mini-boo 
- `/docs/pages/building-your-application/configuring/amp.mdx`@Ubinquitous

**Comment by kmsu44** [comment]
- /docs/pages/building-your-application/configuring/babel.mdx
해당 문서 번역하겠습니다.

**Comment by therealjamesjung** [comment]
- /docs/pages/api-reference/next-config-js/runtime-configuration.mdx
  해당 문서 번역하겠습니다.

**Comment by daejlee** [comment]
- /docs/pages/building-your-application/data-fetching/client-side.mdx
해당 문서 번역하겠습니다.

**Comment by icefoxand** [comment]
/docs/pages/building-your-application/configuring/amp.mdx
해당 페이지 번역하겠습니다!

**Comment by 4anghyeon** [comment]
/docs/pages/building-your-application/rendering/client-side-rendering.mdx
해당 페이지 번역하겠습니다.

**Comment by ironAiken2** [comment]
/docs/pages/building-your-application/data-fetching/forms-and-mutations.mdx
해당 페이지 번역하겠습니다.

**Comment by grapefruit13** [comment]
/docs/pages/building-your-application/Rendering.mdx

해당 문서 번역하겠습니다

**Comment by jiyeon2536** [comment]
/docs/pages/building-your-application/data-fetching/get-server-side-props.mdx

해당 페이지 번역하겠습니다.

**Comment by hansololiviakim** [comment]
/docs/pages/building-your-application/rendering/server-side-rendering.mdx
해당 페이지 번역하겠습니다.

**Comment by luciancah** [comment]
안녕하세요! 많은 참여 정말 감사합니다.
이제 막 시작한 프로젝트이다 보니, 현재 보내주신 PR은 다른 분들께서 기여를 시작하실때 참고하실 수 있도록 일정 기간 유지(1주일 이내) 후 머지하도록 하겠습니다. 다시한번 감사합니다 ☺️

**Comment by yoonncho** [comment]
/docs/pages/building-your-application/routing/custom-document.mdx

해당 문서 번역하겠습니다.

**Comment by f0rever0** [comment]
/docs/pages/building-your-application/data-fetching/get-static-props.mdx

해당 문서 번역하겠습니다!

**Comment by f0rever0** [comment]
/docs/pages/building-your-application/data-fetching/get-static-props.mdx

해당 문서 번역하겠습니다!

**Comment by createhb21** [comment]
/docs/pages/building-your-application/routing/pages-and-layouts.mdx 

해당 문서 번역하겠습니다.

**Comment by gouz7514** [comment]
/docs/pages/building-your-application/data-fetching/get-static-props.mdx

해당 문서 번역 희망합니다!

**Comment by gouz7514** [comment]
/docs/pages/building-your-application/rendering/static-site-generation.mdx

해당 문서 번역 희망합니다!

**Comment by aken-you** [comment]
/docs/pages/building-your-application/routing/dynamic-routes.mdx

해당 문서 번역하겠습니다.

**Comment by leesb971204** [comment]
/docs/pages/building-your-application/routing/api-routes.mdx
해당 문서 번역하겠습니다.

**Comment by imdaxsz** [comment]
/docs/pages/building-your-application/routing/custom-error.mdx

해당 문서 번역하겠습니다.

**Comment by Hongheesun** [comment]
/docs/pages/building-your-application/configuring/debugging.mdx

해당 문서 번역하겠습니다.

**Comment by yoouyeon** [comment]
/docs/pages/building-your-application/routing/linking-and-navigating.mdx
해당 문서 번역하겠습니다 ☺️

**Comment by gkfyr** [comment]
/docs/pages/building-your-application/data-fetching/get-static-paths.mdx
해당 문서 번역하겠습니다.

**Comment by Hongheesun** [comment]
/docs/pages/building-your-application/configuring/error-handling.mdx
해당 문서 추가로 번역하겠습니다!

**Comment by pySoo** [comment]
/docs/pages/building-your-application/deploying/ci-build-caching.mdx
 해당 문서 번역하겠습니다 😊

**Comment by hansololiviakim** [comment]
혹시 추가 작업도 가능할까요? 가능하다면
/docs/pages/building-your-application/upgrading/version-13.mdx
해당 페이지 번역하겠습니다👀

**Comment by luciancah** [comment]
> 혹시 추가 작업도 가능할까요? 가능하다면 /docs/pages/building-your-application/upgrading/version-13.mdx 해당 페이지 번역하겠습니다👀

얼마든지 가능합니다! 감사합니다 :)

**Comment by imdaxsz** [comment]
`/docs/pages/building-your-application/data-fetching/incremental-static-regeneration.mdx`

해당 문서 추가로 번역하겠습니다 :)

**Comment by gkfyr** [comment]
/docs/pages/building-your-application/routing/custom-app.mdx
해당 문서 번역하겠습니다!

**Comment by pySoo** [comment]
/docs/pages/building-your-application/configuring/preview-mode.mdx

해당 문서 추가로 번역하겠습니다! :)

**Comment by dlsxjzld** [comment]
/docs/pages/building-your-application/configuring/custom-server.mdx
해당 문서 번역하겠습니다!

**Comment by RedBe-an** [comment]
/docs/pages/building-your-application/configuring/draft-mode.mdx
해당 문서 번역하겠습니다.

**Comment by RedBe-an** [comment]
/docs/pages/building-your-application/configuring/draft-mode.mdx
해당 문서 번역하겠습니다

**Comment by SoJuSo** [comment]
/docs/pages/building-your-application/configuring/post-css.mdx
해당 문서 번역하겠습니다.

**Comment by RedBe-an** [comment]
/docs/pages/building-your-application/upgrading/version-12.mdx
해당 문서 번역하겠습니다.

**Comment by hansololiviakim** [comment]
/docs/pages/api-reference/functions/get-server-side-props.mdx
해당 문서 번역하겠습니다!

**Comment by grapefruit13** [comment]
/docs/pages/api-reference/functions/get-static-props.mdx

해당 문서 번역하겠습니다

**Comment by SoJuSo** [comment]
/docs/pages/building-your-application/rendering/automatic-static-optimization.mdx
해당 문서 번역하겠습니다!

**Comment by Zero-1016** [comment]
/docs/pages/building-your-application/styling/css-modules.mdx
해당 문서 번역하겠습니다!

**Comment by WaterMinCho** [comment]
/docs/pages/api-reference/functions/use-router.mdx
해당 문서 번역하겠습니다!

**Comment by davindev** [comment]
/docs/pages/building-your-application/routing/internationalization.mdx
해당 문서 번역하고 싶습니다 🤓

**Comment by hyunmyungJaneLee** [comment]
/docs/pages/api-reference/functions/get-initial-props.mdx
해당 문서 번역하고 싶습니다😆

**Comment by pySoo** [comment]
/docs/pages/building-your-application/configuring/draft-mode.mdx
해당 문서 추가로 번역하겠습니다! 😄

**Comment by mini-boo** [comment]
/docs/pages/building-your-application/upgrading/version-9.mdx

해당 문서 번역하겠습니다!

**Comment by miraexhoi** [comment]
/docs/pages/building-your-application/upgrading/version-10.mdx

해당 문서 번역하겠습니다!

**Comment by miraexhoi** [comment]
/docs/pages/building-your-application/upgrading/version-11.mdx

해당 문서 추가로 번역하겠습니다 :)

**Comment by jinlee0310** [comment]
안녕하세요 번역 참여하고 싶은데 혹시 추가적으로 번역 필요하신 문서가 있을까요?

**Comment by luciancah** [comment]
> 안녕하세요 번역 참여하고 싶은데 혹시 추가적으로 번역 필요하신 문서가 있을까요?

안녕하세요 :) 일부 할당 취소된 문서 업데이트 완료했습니다.

**Comment by Ubinquitous** [comment]
/docs/pages/building-your-application/configuring/amp.mdx

해당 문서 번역하고싶습니다!

**Comment by kor-bim** [comment]
/docs/pages/building-your-application/routing/api-routes.mdx
문서 번역하고 싶습니다

**Comment by HarrySeop** [comment]
안녕하세요 블로그 보고 왔습니다! 넥스트 공부 겸 번역 참여하고 싶습니다! 혹시 번역 필요한 문서가 있을까요??

**Comment by 365support** [comment]
번역 필요한 문서 추가로 생기면 할당 받고 싶습니다 !

**Comment by luciancah** [comment]
안녕하세요! 많은 관심 감사합니다. 현재 진행하는 새 문서 번역을 완료하고 나면 문서 업데이트 위주로 2주~4주 간격 이슈 생성 예정입니다.

물론 제가 할당드리는 신규 번역 이슈 이외에도 문서 읽으시다가 발견하시는 오타, 어색한 문장 등 문서 개선을 위한 기여 사항이라면 가리지 않고 환영합니다. 🤗

**Comment by luciancah** [comment]
안녕하세요! 문서 번역에 참여해주신 30분의 컨트리뷰터 분들 덕분에 무사히 한글 문서 번역을 마칠 수 있었습니다.

현재 문서가 베이스로 삼고 있는 원본은 Next.js v15.0.0-canary.82 입니다.
vercel/next.js의 배포 주기 상 문서의 업데이트가 거의 매일 발생하고 있는데요, 이미 RC(Release Candidate) 버전이 지났고, 보통 10월 말에 정식 버전 배포가 진행되기 때문에 잠시 휴식을 거쳐서 10월쯤 문서 업데이트에 대해 새로 이슈 생성해 업데이트 대응하는 것이 어떨까 라고 생각하고 있습니다.
물론 업데이트 이외에도 문서의 개선에 대한 모든 기여사항은 항상 환영합니다. :)

다시 한번 감사의 인사 올립니다 😄 


PS:
추가로, 문서 웹사이트 자체의 SEO 개선도 긍정적으로 이루어지고 있습니다.
`nextjs 한글` 등의 한국어 문서 검색 쿼리에서 상위권을 차지하고 있고, `nextjs + api명` 등의 실제 검색 쿼리에서도 점점 나은 성적을 보이고 있습니다. (전체 평균 20위)
웹사이트 자체의 조회수도 3주만에 10K를 넘었는데요, 참여해주신 기여자분들 덕분입니다 :) 항상 감사합니다.

**Comment by HA-SEUNG-JEONG** [comment]
/docs/pages/api-reference/functions/use-amp.mdx 
해당 부분 번역 가능할까요?

**Comment by sangseophwang** [comment]
/docs/pages/api-reference/next-config-js/transpilePackages.mdx 
이 문서가 없는 것 같은데 번역해 추가해도 괜찮을까요?

**Comment by luciancah** [comment]
> /docs/pages/api-reference/next-config-js/transpilePackages.mdx 이 문서가 없는 것 같은데 추가해도 괜찮을까요?

@sangseophwang 
네 원본 문서에 존재하는데 한글 문서에 없는 부분이라면 물론 가능합니다! 이 이슈는 문서 초안 번역 시점에 편하게 작업 할당 드리기 위해 생성한 이슈라서, 편하신대로 새 이슈나 디스커션 생성해 주셔도 무방합니다 :)
[기여 가이드](https://github.com/luciancah/nextjs-ko/blob/main/CONTRIBUTING.MD) 확인하시면 조금 더 편하게 작업 하실 수 있을듯 합니다 :)
